AshOrSnow/urls.py
from django.contrib import admin
from django.urls import path, include

from weather import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('weather/', include('weather.urls'))
]

weather/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'weather'
urlpatterns = [
    path('', views.home, name='home'),                              
    path('search/', views.search, name='search'),
]

weather/models.py
from django.db import models

class CityLookup(models.Model):
    city = models.CharField(max_length=200)

    def __str__(self):
        return self.city


class Weather(models.Model):
    city = models.ForeignKey(CityLookup, on_delete=models.CASCADE)
    weather = models.CharField(max_length=200, default="")

    def __str__(self):
        return self.weather

class WeatherIcon(models.Model):
    city = models.ForeignKey(CityLookup, on_delete=models.CASCADE)
    weather_icon = models.CharField(max_length=200, default="")

    def __str__(self):
        return self.weather_icon


class Temperature(models.Model):
    city = models.ForeignKey(CityLookup, on_delete=models.CASCADE)
    temperature = models.CharField(max_length=200, default="")

    def __str__(self):
        return self.temperature

AshOrSnow/views.py
from django.shortcuts import render
from django.http import HttpResponse


def weather_view(request, *args, **kwargs):
    return render(request, "home.html", status = 200)

weather/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
import requests, json

from .models import CityLookup, Weather, Temperature, WeatherIcon


def home(request):
    """
    View for the base home page
    """
    return render(request, 'home.html')


def search(request, *args, **kwargs):
    """
    If you are trying to use this code and it does not work you might need your own api key (limited to 50 searches a day)
    This grabs the information input in the search bar and grabs it from the Accuweather Api
    If the search was not spelled correctly or the code limit has been reached it will display the error in except
    Everything under else is taking the data from acuweather and asigning it to the proper module
    Finally the view pulls up the ID of the searched city and redirects to display the results
    """
    
    api_key = 'LXGGpNcbto33jbyFGv0yBADrLm8KEu8y' 
    print(request)
    try:
        # grabs the city that was input 
        input_city = request.POST.get('city')
        city_url = (f"http://dataservice.accuweather.com/locations/v1/cities/search?apikey={api_key}&q={input_city}") 
        city_response = requests.get(city_url).json()[0]["Key"]

    except:
        # Sets up the search again if the code errors for any reason
        return render(request, 'home.html', {
            'error_message': "The city you submitted was not found. Please try again.",
        })

    else:
        # this section of code is where the look up of weather information occurs
        weather_url = (f"http://dataservice.accuweather.com/currentconditions/v1/{city_response}?apikey={api_key}") 
        weather_response = requests.get(weather_url) 
        weather_icon_number = int(weather_response.json()[0]['WeatherIcon']) 

        # the icon url requires 01 and api returns 1 this adds a 0 before the number if less than 10
        if weather_icon_number<10: 
            weather_icon_number = str(weather_icon_number).zfill(2) 
            
        temperature = weather_response.json()[0]['Temperature']['Imperial']['Value']
        weather_type = weather_response.json()[0]['WeatherText'] 
        weather_icon = (f"https://developer.accuweather.com/sites/default/files/{weather_icon_number}-s.png") 

        # Saving searches to database
        new_city = CityLookup(city = input_city)
        new_city.save()

        new_weather = Weather(city = new_city, weather = weather_type) 
        new_weather.save()

        new_temperature = Temperature(city = new_city, temperature = int(temperature))
        new_temperature.save()

        new_weather_icon = WeatherIcon(city = new_city, weather_icon = weather_icon)
        new_weather_icon.save()

        # Redirects to the results page since data is being posted
        new_city_id = new_city.id


        city = get_object_or_404(CityLookup, pk=new_city_id)
        weather = get_object_or_404(Weather, pk=new_city_id)
        temperature = get_object_or_404(Temperature, pk=new_city_id)
        weather_icon = get_object_or_404(WeatherIcon, pk=new_city_id)

        city_proper = str(city).title()

        return render(request, 
                'home.html', 
                {'city': city_proper, 'weather': weather, 
                'temperature': temperature, 'weather_icon': weather_icon})

weather/templates/home.html
<!DOCTYPE html> 
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'weather/style.css' %}">

<head>
    <Title>Weather Search</Title>
    <link rel="shortcut icon" type="image/png" href="https://png.pngtree.com/png-vector/20190629/ourmid/pngtree-sun-icon-design-png-image_1518941.jpg" />
</head>

<body>
    <div class="box">
        <h1>Check the Weather</h1>
    </div>
<form action="{% url 'weather:search' %}" method="post">{% csrf_token %}
    <div class="box">
        <input type="text" name="city" id="city" placeholder="Search a city">
    </div>
    <div class="box">
        <input type="submit" value="Search">
    </div>
</form>

{% if request.path == '/weather/search/' %}
    <p>
        <div class="weather-side"> 
            <div class="container">
                <div class='city-container'>
                    <div class='all-container'>
                        <h2 class="city-name">{{ city }}</h2>
                        <div class="temp">{{ temperature }}°F</div>
                        <div class="weather-type">{{ weather }}</div>
                        <image class="weather-type-icon" src='{{ weather_icon }}'></image>
                    </h2>
                </div>      
            </div>
        </div>
    </p>
    </body>
{% else %}
    <div></div>
{% endif %}